### ISSUE TITLE
Reading signals from other controllers

### ISSUE THREAD

**Issue by wellnesscookie** [thtuerk/microbit-ir-remote#2]
Greetings,

I am wondering if you could help me how to make or recode this library to be working with other controllers. What I am trying is to make an variable that I can use in the forever() block so I can check whether there is signal or not. For an example:

```
forever() {

// Signal received true or false
    if (ired.decode()) {

        // gets which
        long code = ired.result;

        switch(code) 
        case 1234567:
              do that and that; break;
        case 7654321:
              do that and that; break;
    }
}
```

I wish not to listen to an event, but rather use it in microbits forever loop. I know this may not be a place to ask this kind of question, but I hope you can help me or at least tell me how could I do it. Thanks in advance! :)

**Comment by thtuerk** [comment]
Hi, I got the impression that you are looking for a library for reading IR codes with the microbit. This repository does not contain anything like this. It is a small toy to explain the principles of how IR remotes work to children with as simple code as possible. That's why there is busy waiting. And that's why the code is not very reliable at all. It should not be used to read IR codes (too unreliable, too few supported codecs and too incovenient to use). Just use it explain how IR-remotes work (and even there I simplified a few details). 

So, I believe for what you want, this example is not suitable at all. You should look at how to implement a proper IR library using low level code not TypeScript. I have not searched for such a library for some years. Perhaps there is one out there.

**Comment by wellnesscookie** [comment]
First of all, thanks for the answer. I understand and I have been searching for a while. 
This one fits us best: https://github.com/zhuning239/cBit_IR + we use to receive signals from an Arduino (mp3) remote controller as it's hard coded to recognise only it's signals, but I am having a hard time adjusting it to not work only on event, but rather use it in the forever() loop as I described.

I tried to contact the owner of that repository, but no replies from him. Having a hard time figuring it by myself, and if I am going to succeed, it's gonna take a while, but since I am lacking time and need it for a project in less than a week, I am clueless of what to do.

**Comment by thtuerk** [comment]
I don't understand what you try to do and what your problem is. If the code you refer to provides events, why can't you use it in the forever loop? I think I miss something seriously here. If the event fires, put the data into a queue (or perhaps even a single value is fine) and process this data in the forever loop.

What kind of project are you trying to build? Why this one week deadline?

**Comment by wellnesscookie** [comment]
One of the problems is that the event only triggers onPress once, but there is no way to determine whether the button is being held or not. For an example:

I have been using arduino with infrared. There exists a method that returns whether there is a signal being received or not (returns true/false) and there also exists a value of the code that is being sent. If the button is pressed, a hexa decimal code is being put in that value, but if the button was being held, the value variable would refresh itself and contain -1 integer (being sent repeatedly) meaning the the last state is still being transmitted. That way I was able to catch the code of the button that was pressed and still do something with it while it's being held (here the event is not helpful, because it only triggers once and not repeats itself on holding).

The answer to the other question is that I am trying to make controls for my robot to move in a few directions using microbit and IRED remote controller & receiver

I am sorry for the lack of my vocabulary, but I tried to explain as best as I could.

**Comment by thtuerk** [comment]
From the kind of questions you ask, the lack of information and not answering my questions, I strongly suspect that you look for someone doing your school homework for you. I'm not willing to do this.

My lack of motivation is increased by you not providing any information about yourself, not even a name or an email-address for contacts, which in fact forces us to communicate via this issue (which is not intended for such kind of conversations). Since you did not answer my questions and your profile does not contain any information, I have no clue what your background in computer science is and if you are trying to do some project as a hobby, for work or while studying. From your questions and replies I guess you are some high school student who needs help with homework. 

So, I'm closing this issue.
